name: build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        type: string

jobs:

  jlink:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '18'
          architecture: x64

      - name: version
        run: mvn -B versions:set -DnewVersion="${{ inputs.version }}"

      - name: build
        run: mvn --batch-mode clean javafx:jlink

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: target/*.zip

